### ISSUE TITLE
How standard is current JSON format of EnclaveInfo?

### ISSUE THREAD

**Issue by dimakuv** [Azure-Samples/microsoft-azure-attestation#2]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

I would like to re-use the `validatequotes.core` C# utility for Microsoft Azure Attestation (MAA) in Graphene (validatequotes.core).

This utility takes a JSON file as input and sends the request to the MAA service and gets the JWT result back.

According to the MAA standard, the "Attestation Request" to the MAA service only requires two fields:
- Quote (your typical SGX quote provided by the Quoting Enclave)
- Enclave Held Data (basically, SGX report's `reportdata`)

However, the JSON file that the `validatequotes.core` expects has several additional fields: `Type`, `MrenclaveHex`, etc. See for example https://github.com/Azure-Samples/microsoft-azure-attestation/blob/master/intel.sdk.attest.sample/genquotes/out/enclave.info.release.json.

Given that I need to construct the "expected" JSON file in Graphene, do I actually need to specify anything other than the required `Quote` and `Enclave Held Data`? Or to ask differently: is this JSON format only an example or it may be considered standard (if I want to use `validatequotes.core` or a similar utility in the future)?

**Comment by olkroshk** [comment]
@dimakuv you are correct, for the quote validation sample it should be sufficient to pass only quote and enclave held data within the JSON file.

**Comment by gkostal** [comment]
@dimakuv - thanks for reaching out.  

The enclave info JSON file format is only used by the sample code.  In addition to the info required to call the MAA attest API (i.e. quote + enclave-held-data), the enclave info JSON file contains a copy of the values that the sample code believes should be encapsulated in the quote (i.e. type, mrenclavehex, ...).  This is because the sample code will verify that the fields in the JWT token produced by the MAA service match the values used when the enclave was originally compiled.

Closing this issue since it seems resolved.
